<div style="width:180px; height:202px; float:left; margin-right:10px; margin-bottom:10px;">
            <table width="180" height="202" border="0" cellpadding="0" cellspacing="1" bgcolor="#999999">
              <tr>
                <td width="180" height="140" bgcolor="#FFFFFF"><div align="center" style="width:180px; height:140px; overflow:hidden;" ><a href="[field:arcurl/]"><img src="[field:litpic/]" height="140"/></a></div></td>
              </tr>
              <tr>
                <td height="55" bgcolor="#FFFFFF"><div align="center"><a href="[field:arcurl/]" style="color:#000000;">[field:title /]</a></div></td>
              </tr>
            </table>
			</div>