<?php
$z[0]=Array("global","",125,150);
$z[0][4]['name']="cfg_cmsurl";
$z[1]=Array("global","",266,291);
$z[1][4]['name']="cfg_cmsurl";
$z[2]=Array("global","",407,432);
$z[2][4]['name']="cfg_cmsurl";
$z[3]=Array("global","",549,574);
$z[3][4]['name']="cfg_cmsurl";
$z[4]=Array("global","",692,717);
$z[4][4]['name']="cfg_cmsurl";
$z[5]=Array("global","",835,860);
$z[5][4]['name']="cfg_cmsurl";
$z[6]=Array("global","",972,997);
$z[6][4]['name']="cfg_cmsurl";

?>