<?php
$z[0]=Array("channel","\r\n      <li><a href='[field:typeurl/]'>[field:typename/]</a></li>\r\n      ",81,194);
$z[0][4]['type']="son";
$z[1]=Array("sql","  \r\n<li><a href=\"[field:typedir function='str_replace(\"{cmspath}\",\"\",@me)'/]/[field:defaultname/]\">[field:typename/]</a></li>\r\n",298,545);
$z[1][4]['sql']="SELECT typename,typedir,defaultname FROM dede_arctype where reID = 3 ORDER BY sortrank ASC";

?>